if [ -d "${HOME}/.local/bin" ]; then
  PATH="${HOME}/.local/bin:${PATH}"
fi

export VISUAL='/usr/bin/vim'
export EDITOR="${VISUAL}"

export TEXMFHOME="${HOME}/.local/share/texmf"

[ -z "${DISPLAY}" -a "$(fgconsole)" -eq 1 ] && exec startx

